<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genericdiffdata" nsURI="http://www.eclipse.org/emf/diffmerge/generic/1.0.0/diffdata"
    nsPrefix="org.eclipse.emf.diffmerge.generic">
  <eClassifiers xsi:type="ecore:EClass" name="EIdentified" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EComparison" eSuperTypes="#//EIdentified #//IEditableComparison">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ancestorScope" eType="#//IEditableModelScope"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceScope" lowerBound="1"
        eType="#//IEditableModelScope" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" lowerBound="1"
        eType="#//IEditableModelScope" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMatchPolicy" eType="#//IMatchPolicy"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDiffPolicy" eType="#//IDiffPolicy"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMergePolicy" eType="#//IMergePolicy"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="#//EMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMapping" eSuperTypes="#//EIdentified #//IEditableMapping">
    <eOperations name="getComparison" eType="#//EComparison"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiableContents" upperBound="-1"
        eType="#//EMatch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceCompletedMatches"
        upperBound="-1" eType="#//IMatch" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCompletedMatches"
        upperBound="-1" eType="#//IMatch" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMatch" eSuperTypes="#//EIdentified #//IEditableMatch">
    <eOperations name="getMapping" eType="#//EMapping"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchID" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ancestor" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiableRelatedDifferences"
        upperBound="-1" eType="#//EMergeableDifference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiableAttributeMap"
        upperBound="-1" eType="#//AttributeToValueToDifferenceEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiableReferenceMap"
        upperBound="-1" eType="#//ReferenceToElementToDifferenceEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementPresenceDifference"
        eType="#//IElementPresence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOwnershipDifference"
        eType="#//IReferenceValuePresence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOwnershipDifference"
        eType="#//IReferenceValuePresence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMergeableDifference" abstract="true"
      eSuperTypes="#//EIdentified #//IEditableMergeableDifference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparison" lowerBound="1"
        eType="#//EComparison"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignedWithAncestor" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflicting" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignored" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeDestination" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="possibleMergeDestinations"
        upperBound="-1" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explicitDependenciesForTarget"
        upperBound="-1" eType="#//IMergeableDifference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explicitDependenciesForReference"
        upperBound="-1" eType="#//IMergeableDifference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitDependenciesForTarget"
        upperBound="-1" eType="#//IMergeableDifference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitDependenciesForReference"
        upperBound="-1" eType="#//IMergeableDifference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EElementRelativePresence" abstract="true"
      eSuperTypes="#//EMergeableDifference #//IElementRelativePresence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementMatch" lowerBound="1"
        eType="#//EMatch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presenceRole" lowerBound="1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EElementPresence" eSuperTypes="#//EElementRelativePresence #//IElementPresence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerMatch" lowerBound="1"
        eType="#//EMatch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EValuePresence" abstract="true" eSuperTypes="#//EElementRelativePresence #//IValuePresence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributeValuePresence" eSuperTypes="#//EValuePresence #//IAttributeValuePresence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceValuePresence" eSuperTypes="#//EValuePresence #//IReferenceValuePresence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueMatch" eType="#//EMatch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeToValueToDifferenceEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//ValueToDifferenceEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueToDifferenceEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//IAttributeValuePresence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceToElementToDifferenceEntry"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//ElementToDifferenceEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementToDifferenceEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//IReferenceValuePresence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComparison" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IComparison"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableComparison" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IComparison.Editable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMapping" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableMapping" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMapping.Editable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMatch" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMatch"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableMatch" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMatch.Editable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMergeableDifference" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IMergeableDifference"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableMergeableDifference" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IMergeableDifference.Editable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IElementRelativePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IElementRelativePresence"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IElementPresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IElementPresence"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IValuePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IValuePresence"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAttributeValuePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IAttributeValuePresence"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IReferenceValuePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IReferenceValuePresence"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IEditableModelScope" instanceClassName="org.eclipse.emf.diffmerge.generic.api.scopes.IEditableModelScope"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IMatchPolicy" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMatchPolicy"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IDiffPolicy" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IDiffPolicy"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IMergePolicy" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMergePolicy"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Role" instanceClassName="org.eclipse.emf.diffmerge.generic.api.Role"/>
</ecore:EPackage>
