<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gdiffdata" nsURI="http://www.eclipse.org/emf/diffmerge/generic/1.0.0/diffdata"
    nsPrefix="org.eclipse.emf.diffmerge.generic">
  <eClassifiers xsi:type="ecore:EClass" name="EIdentified" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EComparison" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A partial implementation of IComparison based on EMF.&#xA;Type parameter &lt;S> should be understood as &lt;S extends IEditableTreeDataScope&lt;E>>."/>
    </eAnnotations>
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ancestorScope" transient="true">
      <eGenericType eTypeParameter="#//EComparison/S"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceScope" lowerBound="1"
        transient="true">
      <eGenericType eTypeParameter="#//EComparison/S"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" lowerBound="1"
        transient="true">
      <eGenericType eTypeParameter="#//EComparison/S"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMatchPolicy" transient="true">
      <eGenericType eClassifier="#//IMatchPolicy">
        <eTypeArguments eTypeParameter="#//EComparison/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDiffPolicy" transient="true">
      <eGenericType eClassifier="#//IDiffPolicy">
        <eTypeArguments eTypeParameter="#//EComparison/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastMergePolicy" transient="true">
      <eGenericType eClassifier="#//IMergePolicy">
        <eTypeArguments eTypeParameter="#//EComparison/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="#//EMapping">
        <eTypeArguments eTypeParameter="#//EComparison/E"/>
        <eTypeArguments eTypeParameter="#//EComparison/A"/>
        <eTypeArguments eTypeParameter="#//EComparison/R"/>
        <eTypeArguments eTypeParameter="#//EComparison/S"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EIdentified"/>
    <eGenericSuperTypes eClassifier="#//IEditableComparison">
      <eTypeArguments eTypeParameter="#//EComparison/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EComparisonElement" abstract="true"
      interface="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eOperations name="getComparison">
      <eGenericType eClassifier="#//EComparison">
        <eTypeArguments eTypeParameter="#//EComparisonElement/E"/>
        <eTypeArguments eTypeParameter="#//EComparisonElement/A"/>
        <eTypeArguments eTypeParameter="#//EComparisonElement/R"/>
        <eTypeArguments eTypeParameter="#//EComparisonElement/S"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMapping" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiableContents" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//EMatch">
        <eTypeArguments eTypeParameter="#//EMapping/E"/>
        <eTypeArguments eTypeParameter="#//EMapping/A"/>
        <eTypeArguments eTypeParameter="#//EMapping/R"/>
        <eTypeArguments eTypeParameter="#//EMapping/S"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceCompletedMatches"
        upperBound="-1" resolveProxies="false">
      <eGenericType eClassifier="#//IMatch">
        <eTypeArguments eTypeParameter="#//EMapping/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCompletedMatches"
        upperBound="-1" resolveProxies="false">
      <eGenericType eClassifier="#//IMatch">
        <eTypeArguments eTypeParameter="#//EMapping/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EIdentified"/>
    <eGenericSuperTypes eClassifier="#//EComparisonElement">
      <eTypeArguments eTypeParameter="#//EMapping/E"/>
      <eTypeArguments eTypeParameter="#//EMapping/A"/>
      <eTypeArguments eTypeParameter="#//EMapping/R"/>
      <eTypeArguments eTypeParameter="#//EMapping/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IEditableMapping">
      <eTypeArguments eTypeParameter="#//EMapping/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMatch" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eOperations name="getAncestor">
      <eGenericType eTypeParameter="#//EMatch/E"/>
    </eOperations>
    <eOperations name="getReference">
      <eGenericType eTypeParameter="#//EMatch/E"/>
    </eOperations>
    <eOperations name="getTarget">
      <eGenericType eTypeParameter="#//EMatch/E"/>
    </eOperations>
    <eOperations name="setAncestor">
      <eParameters name="e">
        <eGenericType eTypeParameter="#//EMatch/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="setReference">
      <eParameters name="e">
        <eGenericType eTypeParameter="#//EMatch/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="setTarget">
      <eParameters name="e">
        <eGenericType eTypeParameter="#//EMatch/E"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiableRelatedDifferences"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//EMergeableDifference">
        <eTypeArguments eTypeParameter="#//EMatch/E"/>
        <eTypeArguments eTypeParameter="#//EMatch/A"/>
        <eTypeArguments eTypeParameter="#//EMatch/R"/>
        <eTypeArguments eTypeParameter="#//EMatch/S"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementPresenceDifference">
      <eGenericType eClassifier="#//IElementPresence">
        <eTypeArguments eTypeParameter="#//EMatch/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOwnershipDifference">
      <eGenericType eClassifier="#//IReferenceValuePresence">
        <eTypeArguments eTypeParameter="#//EMatch/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOwnershipDifference">
      <eGenericType eClassifier="#//IReferenceValuePresence">
        <eTypeArguments eTypeParameter="#//EMatch/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EIdentified"/>
    <eGenericSuperTypes eClassifier="#//EComparisonElement">
      <eTypeArguments eTypeParameter="#//EMatch/E"/>
      <eTypeArguments eTypeParameter="#//EMatch/A"/>
      <eTypeArguments eTypeParameter="#//EMatch/R"/>
      <eTypeArguments eTypeParameter="#//EMatch/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IEditableMatch">
      <eTypeArguments eTypeParameter="#//EMatch/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMergeableDifference" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignedWithAncestor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflicting" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignored" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeDestination" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="possibleMergeDestinations"
        upperBound="-1" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explicitDependenciesForTarget"
        upperBound="-1">
      <eGenericType eClassifier="#//IMergeableDifference">
        <eTypeArguments eTypeParameter="#//EMergeableDifference/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explicitDependenciesForReference"
        upperBound="-1">
      <eGenericType eClassifier="#//IMergeableDifference">
        <eTypeArguments eTypeParameter="#//EMergeableDifference/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitDependenciesForTarget"
        upperBound="-1">
      <eGenericType eClassifier="#//IMergeableDifference">
        <eTypeArguments eTypeParameter="#//EMergeableDifference/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitDependenciesForReference"
        upperBound="-1">
      <eGenericType eClassifier="#//IMergeableDifference">
        <eTypeArguments eTypeParameter="#//EMergeableDifference/E"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EIdentified"/>
    <eGenericSuperTypes eClassifier="#//EComparisonElement">
      <eTypeArguments eTypeParameter="#//EMergeableDifference/E"/>
      <eTypeArguments eTypeParameter="#//EMergeableDifference/A"/>
      <eTypeArguments eTypeParameter="#//EMergeableDifference/R"/>
      <eTypeArguments eTypeParameter="#//EMergeableDifference/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IEditableMergeableDifference">
      <eTypeArguments eTypeParameter="#//EMergeableDifference/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EElementRelativePresence" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementMatch" lowerBound="1">
      <eGenericType eClassifier="#//EMatch">
        <eTypeArguments eTypeParameter="#//EElementRelativePresence/E"/>
        <eTypeArguments eTypeParameter="#//EElementRelativePresence/A"/>
        <eTypeArguments eTypeParameter="#//EElementRelativePresence/R"/>
        <eTypeArguments eTypeParameter="#//EElementRelativePresence/S"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presenceRole" lowerBound="1"
        eType="#//Role"/>
    <eGenericSuperTypes eClassifier="#//EMergeableDifference">
      <eTypeArguments eTypeParameter="#//EElementRelativePresence/E"/>
      <eTypeArguments eTypeParameter="#//EElementRelativePresence/A"/>
      <eTypeArguments eTypeParameter="#//EElementRelativePresence/R"/>
      <eTypeArguments eTypeParameter="#//EElementRelativePresence/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IElementRelativePresence">
      <eTypeArguments eTypeParameter="#//EElementRelativePresence/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EElementPresence" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerMatch" lowerBound="1">
      <eGenericType eClassifier="#//EMatch">
        <eTypeArguments eTypeParameter="#//EElementPresence/E"/>
        <eTypeArguments eTypeParameter="#//EElementPresence/A"/>
        <eTypeArguments eTypeParameter="#//EElementPresence/R"/>
        <eTypeArguments eTypeParameter="#//EElementPresence/S"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EElementRelativePresence">
      <eTypeArguments eTypeParameter="#//EElementPresence/E"/>
      <eTypeArguments eTypeParameter="#//EElementPresence/A"/>
      <eTypeArguments eTypeParameter="#//EElementPresence/R"/>
      <eTypeArguments eTypeParameter="#//EElementPresence/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IElementPresence">
      <eTypeArguments eTypeParameter="#//EElementPresence/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EValuePresence" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eOperations name="getFeature" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eGenericSuperTypes eClassifier="#//EElementRelativePresence">
      <eTypeArguments eTypeParameter="#//EValuePresence/E"/>
      <eTypeArguments eTypeParameter="#//EValuePresence/A"/>
      <eTypeArguments eTypeParameter="#//EValuePresence/R"/>
      <eTypeArguments eTypeParameter="#//EValuePresence/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IValuePresence">
      <eTypeArguments eTypeParameter="#//EValuePresence/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributeValuePresence" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eOperations name="setAttribute">
      <eParameters name="attribute" lowerBound="1">
        <eGenericType eTypeParameter="#//EAttributeValuePresence/A"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eGenericSuperTypes eClassifier="#//EValuePresence">
      <eTypeArguments eTypeParameter="#//EAttributeValuePresence/E"/>
      <eTypeArguments eTypeParameter="#//EAttributeValuePresence/A"/>
      <eTypeArguments eTypeParameter="#//EAttributeValuePresence/R"/>
      <eTypeArguments eTypeParameter="#//EAttributeValuePresence/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IAttributeValuePresence">
      <eTypeArguments eTypeParameter="#//EAttributeValuePresence/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceValuePresence" abstract="true">
    <eTypeParameters name="E"/>
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
    <eTypeParameters name="S"/>
    <eOperations name="setReference">
      <eParameters name="reference" lowerBound="1">
        <eGenericType eTypeParameter="#//EReferenceValuePresence/R"/>
      </eParameters>
    </eOperations>
    <eOperations name="setValue">
      <eParameters name="value" lowerBound="1">
        <eGenericType eTypeParameter="#//EReferenceValuePresence/E"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueMatch">
      <eGenericType eClassifier="#//EMatch">
        <eTypeArguments eTypeParameter="#//EReferenceValuePresence/E"/>
        <eTypeArguments eTypeParameter="#//EReferenceValuePresence/A"/>
        <eTypeArguments eTypeParameter="#//EReferenceValuePresence/R"/>
        <eTypeArguments eTypeParameter="#//EReferenceValuePresence/S"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//EValuePresence">
      <eTypeArguments eTypeParameter="#//EReferenceValuePresence/E"/>
      <eTypeArguments eTypeParameter="#//EReferenceValuePresence/A"/>
      <eTypeArguments eTypeParameter="#//EReferenceValuePresence/R"/>
      <eTypeArguments eTypeParameter="#//EReferenceValuePresence/S"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//IReferenceValuePresence">
      <eTypeArguments eTypeParameter="#//EReferenceValuePresence/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComparison" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IComparison"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableComparison" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IComparison.Editable"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMapping" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMapping"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableMapping" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMapping.Editable"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMatch" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMatch"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableMatch" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMatch.Editable"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMergeableDifference" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IMergeableDifference"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEditableMergeableDifference" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IMergeableDifference.Editable"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IElementRelativePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IElementRelativePresence"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IElementPresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IElementPresence"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IValuePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IValuePresence"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAttributeValuePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IAttributeValuePresence"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IReferenceValuePresence" instanceClassName="org.eclipse.emf.diffmerge.generic.api.diff.IReferenceValuePresence"
      abstract="true" interface="true">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IEditableTreeDataScope" instanceClassName="org.eclipse.emf.diffmerge.generic.api.scopes.IEditableTreeDataScope">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IMatchPolicy" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMatchPolicy">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IDiffPolicy" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IDiffPolicy">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IMergePolicy" instanceClassName="org.eclipse.emf.diffmerge.generic.api.IMergePolicy">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Role" instanceClassName="org.eclipse.emf.diffmerge.generic.api.Role"/>
</ecore:EPackage>
